# Generated by Django 2.0.7 on 2018-08-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20180819_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
