# Generated by Django 2.0.7 on 2018-08-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_auto_20180819_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
